## Списки

Вам дан список. Поменяйте местами первую и вторую половину списка.

In [2]:
a = [1, 2, 3, 4, 5, 6, 7]
a[:len(a)//2], a[len(a)//2:] = a[len(a)//2:], a[:len(a)//2]
print(a)

[4, 5, 6, 7, 1, 2, 3]


Вам дан список. Поменяйте в нём местами блоки элементов: каждый нечётный со первого по пятый с начала с каждым чётный со второго по пятый с конца. 

In [4]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
a[1:5:2], a[-2: -5: -2] = a[-2: -5: -2], a[1:5:2]
print(a)

[0, 11, 2, 9, 4, 5, 6, 7, 8, 3, 10, 1, 12]


## Генераторы

Вам дан список. Создайте новый список, в котором останутся только чётные элементы кратные трём. 

In [1]:
a = [1, 2, 3, 4, 5, 6, 12, 9, 24, 12]
b = [x for x in a if x % 6 == 0]
print(b)
b = list(filter(lambda x: (x % 6 == 0), a))
print(b)

[6, 12, 24, 12]
[6, 12, 24, 12]


Вам дан список. Для него и ивертированного по порядку списка выведите пары (x, y) в новом списке.

In [2]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b = a[::-1]
p = [(x, y) for x, y in zip(a, b)]
print(p)

[(1, 9), (2, 8), (3, 7), (4, 6), (5, 5), (6, 4), (7, 3), (8, 2), (9, 1)]


## Встроенные функции

Вам дана строка. Выведите сумму ascii-кодов элементов в строке. 

In [3]:
s = "asfsefes13123ww"
res = sum(ord(i) for i in s)
print(res)

1336


Вам дана строка. Выведите строку, выведите пары (элемент строки, порядковый номер).

In [4]:
s = "asfsefes13123ww"
for k, v in enumerate(s):
    print(f'({v}, {k})')

(a, 0)
(s, 1)
(f, 2)
(s, 3)
(e, 4)
(f, 5)
(e, 6)
(s, 7)
(1, 8)
(3, 9)
(1, 10)
(2, 11)
(3, 12)
(w, 13)
(w, 14)


## NumPy

Дан массив 16х16
Создайте новый массив 4х4 , элементы которого будут суммой блоков 4х4 исходного массива

In [5]:
import numpy as np
a = np.ones((16, 16))
b = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        b[i][j] = np.sum(a[i*4: (i + 1)*4, j*4: (j + 1)*4])
print(b)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


Дан массив, вставьте между каждым значением сумму соседних элементов

In [6]:
a = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1])
s = a + a[::-1]
ans = np.empty(len(a) + len(s))
ans[0::2] = a
ans[1::2] = s
print(ans)

[1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2.]


## Pandas

https://www.kaggle.com/datasets/ishadss/productivity-prediction-of-garment-employees

- Какие типы данных присутствуют в датасете?
- Есть ли в датасете пропущенные значения? Если да, то сколько и где?
- Постройте график распределения переменной `actual_productivity`.
- Постройте heatmap для матрицы корреляции числовых переменных в датасете.
- Постройте pairplot для всех переменных.
- Постройте boxplot для всех переменных и выведете объекты которые являются выбросами (строки из датафрейма).
- Посчитайте различные статестические показатели (среднее, медиана, максимум, минимум) для различных категорий в колонке `quarter` *(т.е. отдельно какие показатели у класса quarter1, какие у класса quarter2 и и т.д.)*.
- Разделите колонку `date` на три: день, месяц, год.

In [7]:
import pandas as pd

df = pd.read_csv("archive/garments_worker_productivity.csv")
print(df.dtypes)

date                      object
quarter                   object
department                object
day                       object
team                       int64
targeted_productivity    float64
smv                      float64
wip                      float64
over_time                  int64
incentive                  int64
idle_time                float64
idle_men                   int64
no_of_style_change         int64
no_of_workers            float64
actual_productivity      float64
dtype: object


[sudo] password for dmitry: 

In [9]:
nulls = df.isnull().sum()
print(nulls)

date                       0
quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      506
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_style_change         0
no_of_workers              0
actual_productivity        0
dtype: int64


In [10]:
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
sns.histplot(df['actual_productivity'], kde=True, bins=30)
plt.title('Распределение actual_productivity', fontsize=16)
plt.xlabel('Actual Productivity', fontsize=14)
plt.ylabel('Частота', fontsize=14)
plt.grid(True)
plt.show()


ModuleNotFoundError: No module named 'seaborn'